export const spanishHeading = '¿Qué es el Coaching Viajero?';
export const spanishText = [
    'Partimos de la base de que el coaching es un entrenamiento por medio del cuál adquirirás herramientas para poder descubrir tu propósito, tu propósito viajando.',
    'Aquellos que leen descubrir tu propósito les parecerá quizás un poco esotérico, es verdad, ya que podemos asegurar en una sociedad tan dormida, lo que normalmente se hace es seguir a las masas, seguir al sistema que está impuesto bajo el concepto de normalidad, llevando una vida sin pausa, todo corriendo por encima de las 24 horas diarias que disponemos, sumando al cuerpo un sin números de enfermedades y cohibidos por el stress, envueltos en deudas y atados al romance de la frase un día cambiará.',
    'Pues detente... realmente esa es la vida que deseas vivir?',
    'Entre las comodidades de la mentira rodeada en la zona de confort encontramos las ataduras que para el cerebro imposibles de romper de accionar frente a tus pensamientos autodestructivos, que, esta vida es así. Y ahí estás nuevamente en la rutina como un encantamiento de brujas, sin poder escapar porque te quieres convencer que eso está bien. Pasan los años y así en un intenso año de trabajo, woow qué maravillas, tienen tan solo 14 días de vacaciones, bueno si trabajas en la misma silla más de 10 años tendrás la fortuna de un mes. ¿Impresionante no? Luego de trabajar más de 320 días anuales. Y como no podía ser de otra manera y tu vida va tan a prisas ni te ha dado tiempo de disfrutar esas vacaciones. Haz perdido dos días ya entre vuelos y luego ese poco tiempo contado para llamémosle descansar, que bueno, pues llevas tan altos los niveles de cortisol del stress que te tardará un tiempo significado en normalizarlos y cuando eso empezó a suceder ya estás de nuevo en el avión camino a casa, sin ningún cambio significativo y todo vuelve a ser como antes, pero bueno al menos tengo algunas fotos para subir al Instagram. Claro.',
    'Si todo esto te resuena, pero no quieres ser el de los contados días de vacaciones, es hora que despiertes y emprendas el gran cambio. Tú eres el cambio para ser mejor que tu antigua versión.',
    'Tienes una esencia única, eres el único responsable de tu vida, nuestro equipo desde Amate Viajando deseamos que reacciones y que descubras lo que hay en tu ADN, eres brillante en una sola cosa y ese es tu potencial.',
    '¿Estás listo? Da el sí.',
    'Tu propósito, tu nueva maravillosa vida.',
    'Tu propósito y el viaje de tus sueños dentro de tu verdadero despertar.',
    'Viajando en presencia y en conciencia entramos en la tierra fértil hacia nuestra Libertad.',
    'Viajando el descubrirte será tu pasión, viajando comenzarás a Amarte y valorar lo que verdaderamente te mereces.',
    'AMATE VIAJANDO.',
];